### ISSUE TITLE
[INVALID] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [vinamarora8/Encryptx#1]
Dear Vinam,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by vinamarora8** [comment]
Actually, the program probably includes some functions (eg. getpass) that are linux-specific. I think it would be best if you use Bash for Windows, and compile it in there with gcc as you would do on linux.
